# Generated by Django 5.2.1 on 2025-08-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_address_citymunicipality_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
    ]
