# Generated by Django 5.2.1 on 2025-08-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
